# Generated by Django 5.2.5 on 2025-09-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='in_progress', max_length=20),
        ),
    ]
